### ISSUE TITLE
All errors at Mobile ID side should be logged

### ISSUE THREAD

**Issue by FreddyKaiser** [SCS-CBU-CED-IAM/adfs-mobileid#13]
If you set a mobile number like "testthisnumber" it will generate an error but that is not logged in the Event Log. It should show the mss:101

**Comment by jetfsc** [comment]
In v1.1, this is logged as an exception in "Application and Services Logs\AD FS\Admin". v1.2 adds two logging events in "Application and Services Logs\Swisscom\MobileID\Adfs12\Admin". In case of illegal phone number, no request is sent to the Mobile ID server, thus no server-side error code is recorded.
