### ISSUE TITLE
Make the validation of the MID signature certificate optional (or remove it)

### ISSUE THREAD

**Issue by FreddyKaiser** [SCS-CBU-CED-IAM/adfs-mobileid#15]
There is no more revocation option in the Mobile ID itself (beside if CA will do it). 

Therefore we should make it optional and by default "off" or even remove it completely.

**Comment by jetfsc** [comment]
Already implmented in v1.1. Setting the parameter DisableSignatureCertValidation to True disable the verification of certificate chain. However, same basic checks of the MID user certificate are still be done, e.g. time validity.
