### ISSUE TITLE
SsoOnCancel configuration is raising error

### ISSUE THREAD

**Issue by FreddyKaiser** [SCS-CBU-CED-IAM/adfs-mobileid#18]
When defining `SsoOnCancel="True"` the ADFS Startup raises an error:
![screen shot 2016-03-08 at 08 05 52](https://cloud.githubusercontent.com/assets/4628116/13594551/8d3fda90-e505-11e5-94d3-ce0c2c822592.png)
![screen shot 2016-03-08 at 08 06 06](https://cloud.githubusercontent.com/assets/4628116/13594552/8d5eb726-e505-11e5-921a-a4c15db9e1a3.png)

**Comment by jetfsc** [comment]
Fixed now.

**Comment by FreddyKaiser** [comment]
Tested and ok
